### ISSUE TITLE
Log messages to Security Logger

### ISSUE THREAD

**Issue by robertlemke** [flownative/flow-openidconnect-client#47]
Currently all messages of this package are logged to Flow's default System Logger. However, in applications which authenticate on every or many requests, the actual application log messages can get lost in the amount of OIDC related messages. Therefore, let's log those messages to Flow's Security Logger (`Security.log`) instead.

**Comment by robertlemke** [comment]
Should we consider this a breaking change, because operations might rely on log filters, expecting OIDC messages to appear in System.log? If so, we could make the logger configurable.

On the other hand, given the projects I know using this package, I don't think it is very likely that people rely on such filters.

**Comment by kdambekalns** [comment]
I would not see this as a breaking change. Even if people used log filters and such, then probably in a setup where all messages are collected in the same sink, so the messages would not "disappear", minimizing the impact of the change.
